/**
 * Emoji Shortcode Conversion
 *
 * Converts common emoji shortcodes (like :smiley:) to Unicode emoji.
 * Some XMPP clients send shortcodes instead of actual emoji characters,
 * particularly in reactions (XEP-0444).
 *
 * @example
 * ```typescript
 * import { shortcodeToEmoji, convertShortcodes } from '@fluux/sdk'
 *
 * // Convert a single shortcode
 * shortcodeToEmoji(':thumbsup:')  // → '👍'
 * shortcodeToEmoji('👍')          // → '👍' (unchanged)
 *
 * // Convert array of reactions
 * convertShortcodes([':heart:', ':+1:'])  // → ['❤️', '👍']
 * ```
 *
 * @module Emoji
 */

// Common emoji shortcodes used in messaging apps
// Based on GitHub/Slack/Discord conventions
const EMOJI_SHORTCODES: Record<string, string> = {
  // Smileys & Emotion
  ':grinning:': '😀',
  ':smiley:': '😃',
  ':smile:': '😄',
  ':grin:': '😁',
  ':laughing:': '😆',
  ':satisfied:': '😆',
  ':sweat_smile:': '😅',
  ':rofl:': '🤣',
  ':joy:': '😂',
  ':slightly_smiling_face:': '🙂',
  ':upside_down_face:': '🙃',
  ':wink:': '😉',
  ':blush:': '😊',
  ':innocent:': '😇',
  ':smiling_face_with_three_hearts:': '🥰',
  ':heart_eyes:': '😍',
  ':star_struck:': '🤩',
  ':kissing_heart:': '😘',
  ':kissing:': '😗',
  ':relaxed:': '☺️',
  ':kissing_closed_eyes:': '😚',
  ':kissing_smiling_eyes:': '😙',
  ':yum:': '😋',
  ':stuck_out_tongue:': '😛',
  ':stuck_out_tongue_winking_eye:': '😜',
  ':zany_face:': '🤪',
  ':stuck_out_tongue_closed_eyes:': '😝',
  ':money_mouth_face:': '🤑',
  ':hugs:': '🤗',
  ':thinking:': '🤔',
  ':zipper_mouth_face:': '🤐',
  ':raised_eyebrow:': '🤨',
  ':neutral_face:': '😐',
  ':expressionless:': '😑',
  ':no_mouth:': '😶',
  ':smirk:': '😏',
  ':unamused:': '😒',
  ':roll_eyes:': '🙄',
  ':grimacing:': '😬',
  ':lying_face:': '🤥',
  ':relieved:': '😌',
  ':pensive:': '😔',
  ':sleepy:': '😪',
  ':drooling_face:': '🤤',
  ':sleeping:': '😴',
  ':mask:': '😷',
  ':face_with_thermometer:': '🤒',
  ':face_with_head_bandage:': '🤕',
  ':nauseated_face:': '🤢',
  ':sneezing_face:': '🤧',
  ':hot_face:': '🥵',
  ':cold_face:': '🥶',
  ':woozy_face:': '🥴',
  ':dizzy_face:': '😵',
  ':exploding_head:': '🤯',
  ':cowboy_hat_face:': '🤠',
  ':partying_face:': '🥳',
  ':sunglasses:': '😎',
  ':nerd_face:': '🤓',
  ':monocle_face:': '🧐',
  ':confused:': '😕',
  ':worried:': '😟',
  ':slightly_frowning_face:': '🙁',
  ':frowning_face:': '☹️',
  ':open_mouth:': '😮',
  ':hushed:': '😯',
  ':astonished:': '😲',
  ':flushed:': '😳',
  ':pleading_face:': '🥺',
  ':frowning:': '😦',
  ':anguished:': '😧',
  ':fearful:': '😨',
  ':cold_sweat:': '😰',
  ':disappointed_relieved:': '😥',
  ':cry:': '😢',
  ':sob:': '😭',
  ':scream:': '😱',
  ':confounded:': '😖',
  ':persevere:': '😣',
  ':disappointed:': '😞',
  ':sweat:': '😓',
  ':weary:': '😩',
  ':tired_face:': '😫',
  ':yawning_face:': '🥱',
  ':triumph:': '😤',
  ':rage:': '😡',
  ':pout:': '😡',
  ':angry:': '😠',
  ':cursing_face:': '🤬',
  ':smiling_imp:': '😈',
  ':imp:': '👿',
  ':skull:': '💀',
  ':skull_and_crossbones:': '☠️',
  ':poop:': '💩',
  ':hankey:': '💩',
  ':clown_face:': '🤡',
  ':japanese_ogre:': '👹',
  ':japanese_goblin:': '👺',
  ':ghost:': '👻',
  ':alien:': '👽',
  ':space_invader:': '👾',
  ':robot:': '🤖',

  // Gestures & Body Parts
  ':wave:': '👋',
  ':raised_back_of_hand:': '🤚',
  ':raised_hand:': '✋',
  ':hand:': '✋',
  ':vulcan_salute:': '🖖',
  ':ok_hand:': '👌',
  ':pinching_hand:': '🤏',
  ':v:': '✌️',
  ':crossed_fingers:': '🤞',
  ':love_you_gesture:': '🤟',
  ':metal:': '🤘',
  ':call_me_hand:': '🤙',
  ':point_left:': '👈',
  ':point_right:': '👉',
  ':point_up_2:': '👆',
  ':middle_finger:': '🖕',
  ':point_down:': '👇',
  ':point_up:': '☝️',
  ':+1:': '👍',
  ':thumbsup:': '👍',
  ':-1:': '👎',
  ':thumbsdown:': '👎',
  ':fist:': '✊',
  ':fist_raised:': '✊',
  ':facepunch:': '👊',
  ':fist_oncoming:': '👊',
  ':punch:': '👊',
  ':fist_left:': '🤛',
  ':fist_right:': '🤜',
  ':clap:': '👏',
  ':raised_hands:': '🙌',
  ':open_hands:': '👐',
  ':palms_up_together:': '🤲',
  ':handshake:': '🤝',
  ':pray:': '🙏',
  ':writing_hand:': '✍️',
  ':nail_care:': '💅',
  ':selfie:': '🤳',
  ':muscle:': '💪',
  ':eyes:': '👀',
  ':eye:': '👁️',
  ':ear:': '👂',
  ':nose:': '👃',
  ':brain:': '🧠',
  ':lips:': '👄',
  ':tongue:': '👅',

  // Hearts & Symbols
  ':heart:': '❤️',
  ':red_heart:': '❤️',
  ':orange_heart:': '🧡',
  ':yellow_heart:': '💛',
  ':green_heart:': '💚',
  ':blue_heart:': '💙',
  ':purple_heart:': '💜',
  ':black_heart:': '🖤',
  ':brown_heart:': '🤎',
  ':white_heart:': '🤍',
  ':broken_heart:': '💔',
  ':heartpulse:': '💗',
  ':heartbeat:': '💓',
  ':two_hearts:': '💕',
  ':revolving_hearts:': '💞',
  ':cupid:': '💘',
  ':sparkling_heart:': '💖',
  ':gift_heart:': '💝',
  ':heart_decoration:': '💟',
  ':heavy_heart_exclamation:': '❣️',
  ':100:': '💯',
  ':anger:': '💢',
  ':boom:': '💥',
  ':collision:': '💥',
  ':dizzy:': '💫',
  ':sweat_drops:': '💦',
  ':dash:': '💨',
  ':hole:': '🕳️',
  ':bomb:': '💣',
  ':speech_balloon:': '💬',
  ':thought_balloon:': '💭',
  ':zzz:': '💤',
  ':fire:': '🔥',
  ':flame:': '🔥',
  ':star:': '⭐',
  ':star2:': '🌟',
  ':sparkles:': '✨',
  ':zap:': '⚡',
  ':sunny:': '☀️',
  ':rainbow:': '🌈',
  ':cloud:': '☁️',
  ':snowflake:': '❄️',
  ':umbrella:': '☔',

  // Celebrations & Objects
  ':tada:': '🎉',
  ':confetti_ball:': '🎊',
  ':balloon:': '🎈',
  ':gift:': '🎁',
  ':trophy:': '🏆',
  ':medal_sports:': '🏅',
  ':medal_military:': '🎖️',
  ':1st_place_medal:': '🥇',
  ':2nd_place_medal:': '🥈',
  ':3rd_place_medal:': '🥉',
  ':crown:': '👑',
  ':gem:': '💎',
  ':moneybag:': '💰',
  ':dollar:': '💵',
  ':credit_card:': '💳',
  ':bell:': '🔔',
  ':no_bell:': '🔕',
  ':mega:': '📣',
  ':loudspeaker:': '📢',
  ':musical_note:': '🎵',
  ':notes:': '🎶',
  ':microphone:': '🎤',
  ':headphones:': '🎧',
  ':guitar:': '🎸',
  ':piano:': '🎹',
  ':saxophone:': '🎷',
  ':trumpet:': '🎺',
  ':violin:': '🎻',
  ':drum:': '🥁',
  ':movie_camera:': '🎥',
  ':camera:': '📷',
  ':camera_flash:': '📸',
  ':video_camera:': '📹',
  ':tv:': '📺',
  ':computer:': '💻',
  ':keyboard:': '⌨️',
  ':desktop_computer:': '🖥️',
  ':printer:': '🖨️',
  ':phone:': '📱',
  ':iphone:': '📱',
  ':telephone:': '📞',
  ':pager:': '📟',
  ':fax:': '📠',
  ':bulb:': '💡',
  ':flashlight:': '🔦',
  ':candle:': '🕯️',
  ':book:': '📖',
  ':books:': '📚',
  ':bookmark:': '🔖',
  ':label:': '🏷️',
  ':envelope:': '✉️',
  ':email:': '📧',
  ':mailbox:': '📫',
  ':package:': '📦',
  ':pencil:': '✏️',
  ':pencil2:': '✏️',
  ':pen:': '🖊️',
  ':fountain_pen:': '🖋️',
  ':paintbrush:': '🖌️',
  ':crayon:': '🖍️',
  ':memo:': '📝',
  ':file_folder:': '📁',
  ':clipboard:': '📋',
  ':calendar:': '📅',
  ':date:': '📅',
  ':pushpin:': '📌',
  ':paperclip:': '📎',
  ':scissors:': '✂️',
  ':lock:': '🔒',
  ':unlock:': '🔓',
  ':key:': '🔑',
  ':hammer:': '🔨',
  ':axe:': '🪓',
  ':wrench:': '🔧',
  ':screwdriver:': '🪛',
  ':gear:': '⚙️',
  ':link:': '🔗',
  ':chains:': '⛓️',
  ':magnet:': '🧲',
  ':hourglass:': '⌛',
  ':watch:': '⌚',
  ':alarm_clock:': '⏰',
  ':stopwatch:': '⏱️',
  ':timer_clock:': '⏲️',
  ':battery:': '🔋',
  ':electric_plug:': '🔌',

  // Food & Drink
  ':coffee:': '☕',
  ':tea:': '🍵',
  ':sake:': '🍶',
  ':beer:': '🍺',
  ':beers:': '🍻',
  ':wine_glass:': '🍷',
  ':cocktail:': '🍸',
  ':tropical_drink:': '🍹',
  ':champagne:': '🍾',
  ':pizza:': '🍕',
  ':hamburger:': '🍔',
  ':fries:': '🍟',
  ':hotdog:': '🌭',
  ':taco:': '🌮',
  ':burrito:': '🌯',
  ':popcorn:': '🍿',
  ':cake:': '🍰',
  ':birthday:': '🎂',
  ':cookie:': '🍪',
  ':doughnut:': '🍩',
  ':chocolate_bar:': '🍫',
  ':candy:': '🍬',
  ':lollipop:': '🍭',
  ':ice_cream:': '🍨',
  ':icecream:': '🍦',
  ':apple:': '🍎',
  ':green_apple:': '🍏',
  ':banana:': '🍌',
  ':orange:': '🍊',
  ':tangerine:': '🍊',
  ':lemon:': '🍋',
  ':watermelon:': '🍉',
  ':grapes:': '🍇',
  ':strawberry:': '🍓',
  ':peach:': '🍑',
  ':cherries:': '🍒',
  ':avocado:': '🥑',
  ':eggplant:': '🍆',
  ':carrot:': '🥕',
  ':corn:': '🌽',
  ':hot_pepper:': '🌶️',
  ':broccoli:': '🥦',
  ':mushroom:': '🍄',
  ':peanuts:': '🥜',

  // Animals
  ':dog:': '🐕',
  ':dog2:': '🐕',
  ':cat:': '🐈',
  ':cat2:': '🐈',
  ':mouse:': '🐁',
  ':mouse2:': '🐁',
  ':hamster:': '🐹',
  ':rabbit:': '🐰',
  ':rabbit2:': '🐇',
  ':fox_face:': '🦊',
  ':bear:': '🐻',
  ':panda_face:': '🐼',
  ':koala:': '🐨',
  ':tiger:': '🐯',
  ':tiger2:': '🐅',
  ':lion:': '🦁',
  ':cow:': '🐮',
  ':cow2:': '🐄',
  ':pig:': '🐷',
  ':pig2:': '🐖',
  ':pig_nose:': '🐽',
  ':frog:': '🐸',
  ':monkey_face:': '🐵',
  ':monkey:': '🐒',
  ':see_no_evil:': '🙈',
  ':hear_no_evil:': '🙉',
  ':speak_no_evil:': '🙊',
  ':chicken:': '🐔',
  ':penguin:': '🐧',
  ':bird:': '🐦',
  ':eagle:': '🦅',
  ':duck:': '🦆',
  ':owl:': '🦉',
  ':bat:': '🦇',
  ':wolf:': '🐺',
  ':boar:': '🐗',
  ':horse:': '🐴',
  ':unicorn:': '🦄',
  ':bee:': '🐝',
  ':honeybee:': '🐝',
  ':bug:': '🐛',
  ':butterfly:': '🦋',
  ':snail:': '🐌',
  ':beetle:': '🪲',
  ':ant:': '🐜',
  ':spider:': '🕷️',
  ':spider_web:': '🕸️',
  ':scorpion:': '🦂',
  ':crab:': '🦀',
  ':snake:': '🐍',
  ':turtle:': '🐢',
  ':tropical_fish:': '🐠',
  ':fish:': '🐟',
  ':blowfish:': '🐡',
  ':dolphin:': '🐬',
  ':whale:': '🐳',
  ':whale2:': '🐋',
  ':shark:': '🦈',
  ':octopus:': '🐙',
  ':shell:': '🐚',
  ':crocodile:': '🐊',
  ':dragon:': '🐉',
  ':dragon_face:': '🐲',
  ':dinosaur:': '🦕',
  ':t-rex:': '🦖',

  // Checkmarks & Indicators
  ':white_check_mark:': '✅',
  ':heavy_check_mark:': '✔️',
  ':ballot_box_with_check:': '☑️',
  ':x:': '❌',
  ':negative_squared_cross_mark:': '❎',
  ':exclamation:': '❗',
  ':heavy_exclamation_mark:': '❗',
  ':question:': '❓',
  ':grey_exclamation:': '❕',
  ':grey_question:': '❔',
  ':warning:': '⚠️',
  ':no_entry:': '⛔',
  ':no_entry_sign:': '🚫',
  ':o:': '⭕',
  ':heavy_multiplication_x:': '✖️',
  ':heavy_plus_sign:': '➕',
  ':heavy_minus_sign:': '➖',
  ':heavy_division_sign:': '➗',
  ':infinity:': '♾️',
  ':recycle:': '♻️',
  ':arrow_up:': '⬆️',
  ':arrow_down:': '⬇️',
  ':arrow_left:': '⬅️',
  ':arrow_right:': '➡️',
  ':arrow_upper_right:': '↗️',
  ':arrow_lower_right:': '↘️',
  ':arrow_lower_left:': '↙️',
  ':arrow_upper_left:': '↖️',
  ':arrow_up_down:': '↕️',
  ':left_right_arrow:': '↔️',
  ':leftwards_arrow_with_hook:': '↩️',
  ':arrow_right_hook:': '↪️',
  ':arrow_heading_up:': '⤴️',
  ':arrow_heading_down:': '⤵️',
  ':arrows_clockwise:': '🔃',
  ':arrows_counterclockwise:': '🔄',
  ':back:': '🔙',
  ':end:': '🔚',
  ':on:': '🔛',
  ':soon:': '🔜',
  ':top:': '🔝',

  // Misc common ones
  ':ok:': '🆗',
  ':sos:': '🆘',
  ':information_source:': 'ℹ️',
  ':abc:': '🔤',
  ':abcd:': '🔡',
  ':1234:': '🔢',
  ':symbols:': '🔣',
  ':capital_abcd:': '🔠',
  ':a:': '🅰️',
  ':b:': '🅱️',
  ':ab:': '🆎',
  ':cl:': '🆑',
  ':cool:': '🆒',
  ':free:': '🆓',
  ':id:': '🆔',
  ':new:': '🆕',
  ':ng:': '🆖',
  ':parking:': '🅿️',
  ':up:': '🆙',
  ':vs:': '🆚',
  ':koko:': '🈁',
  ':accept:': '🉑',
  ':ideograph_advantage:': '🉐',
  ':congratulations:': '㊗️',
  ':secret:': '㊙️',
  ':registered:': '®️',
  ':tm:': '™️',
  ':copyright:': '©️',

  // Sports & Activities
  ':soccer:': '⚽',
  ':basketball:': '🏀',
  ':football:': '🏈',
  ':baseball:': '⚾',
  ':softball:': '🥎',
  ':tennis:': '🎾',
  ':volleyball:': '🏐',
  ':rugby_football:': '🏉',
  ':8ball:': '🎱',
  ':ping_pong:': '🏓',
  ':badminton:': '🏸',
  ':goal_net:': '🥅',
  ':ice_hockey:': '🏒',
  ':field_hockey:': '🏑',
  ':lacrosse:': '🥍',
  ':cricket_game:': '🏏',
  ':golf:': '⛳',
  ':bow_and_arrow:': '🏹',
  ':fishing_pole_and_fish:': '🎣',
  ':boxing_glove:': '🥊',
  ':martial_arts_uniform:': '🥋',
  ':running_shirt_with_sash:': '🎽',
  ':skateboard:': '🛹',
  ':ski:': '🎿',
  ':sled:': '🛷',
  ':ice_skate:': '⛸️',
  ':video_game:': '🎮',
  ':joystick:': '🕹️',
  ':game_die:': '🎲',
  ':chess_pawn:': '♟️',
  ':dart:': '🎯',
  ':bowling:': '🎳',
}

/**
 * Convert emoji shortcodes to Unicode emoji.
 * If the input is already a Unicode emoji or not a recognized shortcode, returns it unchanged.
 *
 * @param text - The text that might be an emoji shortcode (e.g., ":smiley:")
 * @returns The Unicode emoji if it's a recognized shortcode, otherwise the original text
 */
export function shortcodeToEmoji(text: string): string {
  // Check if it's a shortcode format (starts and ends with colons)
  if (!text.startsWith(':') || !text.endsWith(':')) {
    return text
  }

  // Look up in our mapping (case-insensitive)
  const normalized = text.toLowerCase()
  return EMOJI_SHORTCODES[normalized] ?? text
}

/**
 * Convert all emoji shortcodes in an array to Unicode emoji.
 *
 * @param emojis - Array of emoji strings (could be shortcodes or Unicode)
 * @returns Array with shortcodes converted to Unicode emoji
 */
export function convertShortcodes(emojis: string[]): string[] {
  return emojis.map(shortcodeToEmoji)
}
